# No clear secrets in git. Ciphertext only; the in-cluster sealed-secrets
# controller unseals it into Secret ssprint0-secrets (envFrom). Sealed (strict
# scope) against the dev cluster cert for namespace sdk-apps-dev.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ssprint0-secrets
  namespace: sdk-apps-dev
spec:
  encryptedData:
    INTERACTIVE_SECRET: AgB/+aOpJRh8xcETn2E9SnwxnNviuXQsjlIxywftHw4T4CFCavWdf7Xhd+72dTEkjK3U3kQQY4LlmG7wqmDyFxsvH6J2V7qYnCR/+oVrleejk3COMXdRrZiv02NZm2vJfLYdk6Mq2RM0TuQTCyYToSHJiyGv1INpmZ+PtmZQ/4xtqCSgx2aJQsNFMIt37aeGk/H/sU/Y5pRO7l2qM5QKGr+/qN6B6l74cTddISuIXA4RPPAmfS2vPuXOhav7O4z82/gXD3FuTxjBNAklto5zcfAtO6DHWMTMpv4yyQ0Bmug/HxgWO5+iTRTVKRN3CXmcqxd1QkfojmXUVrAwoDFJYm0Suj/aAyvcqb09kVTgaxk1T3923E0pn5RdLcfSaFeoKt1UEq9zsae3muq9nrzi35yLrez8UFwrxyDpHg7q1Z45VqfV8XMoKmj80AG86QOP/B1lBAd6YveK65KgcsPxIorV3ZP/xEcbqpW8wDner9Cdug45jDOmsWMhOfG5Brhkx03ComoGhIiSD0Zq9BzTvLHeU/UZQA7KTqIQtB5EVjGwd67is5Wv8cZ/YVe8knnWvPQ5SjGHjFY8EsmDyo6WiQuMEr06faukke3dBP1XCY+eHjqj2s4/o4usMhNF+XWumJIQyxPeYpFo+hGYEdpF0bk6G+AO/RCNGvQmpwd4O4J3Q/CagwvfOJuoZ2GR1EEDH+KHzjoPM+Z34QtBbJqCTb5p7WB+cKI1lHqN3lbOAs7rmKb1t9GVblRnTjc26PHS3Cc=
  template:
    metadata:
      name: ssprint0-secrets
      namespace: sdk-apps-dev
    type: Opaque
