apiVersion: v1
kind: ConfigMap
metadata:
  name: ssprint0-config
  labels:
    app.kubernetes.io/name: ssprint0
data:
  INSTANCE_DOMAIN: "api.topia.io"
  INSTANCE_PROTOCOL: "https"
  INTERACTIVE_KEY: "w0uH6fStox9osHx20rmq"
  NODE_ENV: "production"
  PORT: "3000"
