apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ssprint0
  labels:
    app.kubernetes.io/name: ssprint0
  annotations:
    alb.ingress.kubernetes.io/group.name: topia-dev
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-path: /api/system/health
spec:
  ingressClassName: alb
  rules:
    - host: ssprint0-dev-topia.topia-rtsdk.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ssprint0
                port:
                  number: 80
